# Docker Compose file for Dev deployment of the backend in Release configuration

services:
  # The container for the monolithic backend
  backend:
    build:
      context: ./backend
      dockerfile: release.Dockerfile
    # Name of the container
    container_name: backend
    # The container will always be restarted
    restart: always
    ports:
      # The port 8080 of the machine is mapped into the port 8080 of the container
      - "8080:8080"
    depends_on:
      # Depends on the PostgreSQL container working healthily
      postgres-dev:
        condition: service_healthy
    networks:
      # The container uses the internal network "backend-net-dev" to communicate with the database
      - backend-net-dev
      # The container uses the external network "website-net-dev" to communicate with the frontend container
      - website-net-dev
    volumes:
      - ./dev/uploads/product-images:/uploads/product-images
    environment:
      # The container will be run in the dev environment
      - SPRING_PROFILES_ACTIVE=dev

  # The container for the dev database
  postgres-dev:
    # Name of the container
    container_name: postgres-dev
    image: postgres:17.4
    # The container will always be restarted
    restart: always
    # Volumes to be used by the container
    volumes:
      # The volume for the database
      - postgres-dev_data:/var/lib/postgresql/data
    networks:
      # The container uses the internal network "backend-net-dev"
      - backend-net-dev
    ports:
      # The port 5433 of the machine is mapped into the port 5432 of the container
      # In order to distinguish from the connections for the production database
      - "5433:5432"
    # Environment variables for the connection
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_admin_pwd
      - POSTGRES_DB=project_db
    # The health check performed for the container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      # The health check will be performed every 5 seconds
      interval: 5s
      # The command must be completed in 5 seconds
      timeout: 5s
      # After 10 retries, the container will be marked as unhealthy
      retries: 10

# Declaration of the volume for the database
volumes:
  postgres-dev_data:

# The common networks for the containers
networks:
  # backend-net-dev is the internal network
  backend-net-dev:
    driver: bridge
  # website-net-dev is the external network
  website-net-dev:
    external: true