server:
  # The gateway will run on the port 8080
  port: 8081

spring:
  application:
    # The name of the Spring Boot application
    name: user-service
eureka:
  instance:
    # The Eureka client exposes itself with its IP address for easier discovery
    preferIpAddress: true
  client:
    # Eureka client can register itself to the Eureka server
    register-with-eureka: true
    # Eureka client can fetch service registry from Eureka server
    fetch-registry: true
    # Service URL is set in application-dev.yml and application-prod.yml