server:
  # The gateway will run on the port 8080
  port: 8080

spring:
  application:
    # The name of the Spring Boot application
    name: gateway
  cloud:
    gateway:
      routes:
        # Routing for the user microservice
        - id: user-service-route # The ID of the route
          uri: lb://user-service # Eureka load-balanced URI for the user microservice
          predicates:
            - Path=/v1/user/** # The HTTP request path for the user microservice
eureka:
  instance:
    # The Eureka client exposes itself with its IP address for easier discovery
    preferIpAddress: true
  client:
    # Eureka client can register itself to the Eureka server
    register-with-eureka: true
    # Eureka client can fetch service registry from Eureka server
    fetch-registry: true
    # Service URL is set in application-dev.yml and application-prod.yml