# Enable logging for the dev environment
logging:
    level:
        # All logs have a minimum level of INFO
        root: INFO
        # The logs related to our codes have a level of DEBUG
        '[com.cs308.gateway]': DEBUG
        # The logs related to Eureka have a level of DEBUG
        '[org.springframework.cloud.netflix.eureka]': DEBUG
        # The logs related to Spring Reactive Gateway have a level of DEBUG
        '[org.springframework.cloud.gateway]': DEBUG
    file:
        # Path for the Docker container's file system
        path: /app/log/prod
        name: gateway.log

eureka:
    client:
        service-url:
            # URL of the Eureka Server (specifically points to the Docker container)
            defaultZone: http://eureka-server:8761/eureka