# Enable logging for the dev environment
logging:
    level:
        # All logs have a minimum level of DEBUG
        root: DEBUG
        # The logs related to our codes have a level of TRACE (the most verbose one)
        '[com.cs308.user_service]': TRACE
        # The logs related to Eureka have a level of TRACE
        '[org.springframework.cloud.netflix.eureka]': TRACE
        # The logs related to Spring Web have a level of TRACE
        '[org.springframework.web]': TRACE
    file:
        # Path for the Docker container's file system
        path: /app/log/dev
        name: user-service.log

eureka:
    client:
        service-url:
            # URL of the Eureka Server (specifically points to the Docker container)
            defaultZone: http://eureka-server-dev:8761/eureka

spring:
    datasource:
        # Connection info for the dev database
        url: jdbc:postgresql://postgres-dev:5432/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
        username: ${POSTGRES_USERSERVICE_USER}
        password: ${POSTGRES_USERSERVICE_PASSWORD}
        driver-class-name: org.postgresql.Driver
        # The connection pooling library used by Spring Boot as default
        # Opens and keeps of a pool of database connections that are available
        hikari:
            # Up to 10 connections can be in use at the same times
            maximum-pool-size: 10
            # The minimum number of idle connections to be maintained in the pool
            minimum-idle: 5