# Enable logging for the dev environment
logging:
    level:
        # All logs have a minimum level of DEBUG
        root: DEBUG
        # The logs related to our codes have a level of TRACE (the most verbose one)
        '[com.cs308.eureka_server]': TRACE
        # The logs related to Eureka have a level of TRACE
        '[org.springframework.cloud.netflix.eureka]': TRACE
    file:
        # Path for the Docker container's file system
        path: /app/log/dev
        name: eureka-server.log

eureka:
    instance:
        # Eureka server exposes itself with its hostname
        hostname: ${spring.application.name}-dev
    client:
        service-url:
            # The address of the Eureka server
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka