server:
  # The Eureka Server will run on the port 8761, conventional for Eureka
  port: 8761

spring:
    application:
      # The name of the Spring Boot application
      name: eureka-server
  
eureka:
    instance:
      # Hostname is defined in application-dev.yml and application-prod.yml
      prefer-ip-address: false
    client:
      # Eureka server does not register itself to the Eureka server
      register-with-eureka: false
      # Eureka server does not fetch service registry from Eureka server
      fetch-registry: false
      # The address of the Eureka server is defined in application-dev.yml and application-prod.yml