# Enable logging for the dev environment
logging:
    level:
        # All logs have a minimum level of INFO
        root: INFO
        # The logs related to our codes have a level of DEBUG
        '[com.cs308.backend]': DEBUG
        # The logs related to Spring Web have a level of DEBUG
        '[org.springframework.web]': DEBUG
        # The logs related to Flyway have a level of DEBUG
        '[org.flywaydb]': DEBUG
    file:
        # Path for the Docker container's file system
        path: /app/log/dev
        name: backend.log

spring:
    datasource:
        # Connection info for the dev database
        url: jdbc:postgresql://postgres-dev:5432/project_db?currentSchema=public
        username: postgres
        password: pg_admin_pwd
        driver-class-name: org.postgresql.Driver