name: Deploy to Prod Environment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1.2.0

      - name: Run the tests
        run: docker compose -f docker-compose.test.yml up --build -d
      
      - name: Create external Docker network
        run: docker network create --driver bridge website-net

      - name: Deploy Docker Compose Prod
        run: docker compose -f docker-compose.prod.release.yml up --build -d
